version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: automo-postgres-prod
    environment:
      POSTGRES_DB: automo_db
      POSTGRES_USER: automo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-automo123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "automo"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: automo-pgadmin-prod
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@automo.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    depends_on:
      - postgres
    volumes:
      - pgadmin_data_prod:/var/lib/pgadmin

  app:
    image: ${IMAGE:-automo-app}:${TAG:-latest}
    container_name: automo-app-prod
    ports:
      - "${HOST_PORT:-8081}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/automo_db
      SPRING_DATASOURCE_USERNAME: automo
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-automo123}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_PROFILES_ACTIVE: prod
      # Configurações de Email
      SPRING_MAIL_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SPRING_MAIL_PORT: ${SMTP_PORT:-587}
      SPRING_MAIL_USERNAME: ${SMTP_USERNAME:-no-reply@automo.com}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      # Configurações de JWT
      APPLICATION_SECURITY_JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      APPLICATION_SECURITY_JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_EXPIRATION:-604800000}
      # Configurações de SMS
      SMS_PROVIDER_ENABLED: ${SMS_ENABLED:-false}
      SMS_PROVIDER_API_KEY: ${SMS_API_KEY}
      SMS_PROVIDER_SENDER: ${SMS_SENDER:-AUTOMO}
    restart: unless-stopped
    volumes:
      - ${UPLOAD_FOLDER:-./storage}:/app/storage

volumes:
  postgres_data_prod:
  pgadmin_data_prod: 